apiVersion: apps/v1
kind: Deployment
metadata:
  name: pan-index-okteto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pan-index-okteto
  template:
    metadata:
      labels:
        app: pan-index-okteto
    spec:
      containers:
        - image: okteto.dev/pan-index-okteto:latest
          name: pan-index-okteto
          ports:
            - containerPort: 5238
          env:
            - name: PAN_INDEX_VERSION
              value: "v3.0.4"