apiVersion: v1
kind: Service
metadata:
  name: pan-index-okteto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "pan-index-okteto"
      port: 5238
  selector:
    app: pan-index-okteto